version: "3.7"

services:
  users-app-database:
    image: postgres
    container_name: users-app-database
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=users-app
    volumes:
      - pgdata:/data/postgres
  users-app:
    build: .
    container_name: users-app
    ports:
      - "3333:3333"
      - "9229:9229"
    volumes:
      - .:/usr/app
    links:
      - users-app-database
    depends_on:
      - users-app-database

volumes:
  pgdata:
    driver: local
